/**
 * Niveshaay image-service — Puppeteer P&L PNG renderer.
 * ---------------------------------------------------------------------------
 * The ONLY external service the WhatsApp branch needs. The n8n "Render Image"
 * node POSTs the standardized P&L JSON here; we render the same styled green
 * card the UI shows (ui.html) and return it as a PNG (base64), which the
 * "Send to WhatsApp" node forwards to Evolution sendMedia.
 *
 *   POST /generate-image   { data: { company_name, quarter_type, row1..rowN } }
 *                       ->  { base64: "<png-without-data-uri-prefix>" }
 *   GET  /health        ->  { ok: true }
 *
 * Styling/highlight/negative logic mirrors ui.html so the WhatsApp image
 * matches the in-browser "Download PNG".
 * ---------------------------------------------------------------------------
 */
const express = require("express");
const puppeteer = require("puppeteer-core");

const PORT = process.env.PORT || 3001;
const EXECUTABLE = process.env.PUPPETEER_EXECUTABLE_PATH || "/usr/bin/chromium";

// ── P&L -> HTML (mirrors ui.html buildTable/buildCard) ───────────────────────
const HL = ["revenue", "gross profit", "ebitda", "total expenses", "profit before tax", "profit/loss before tax", "pat", "eps"];
function isHl(label) {
  const l = String(label || "").toLowerCase();
  return HL.some((k) => l === k || l.indexOf(k) === 0) || l.indexOf("ebitda") > -1 || l === "revenue";
}
function isNeg(v) {
  if (!v) return false;
  const c = String(v).replace(/[%,]/g, "").trim();
  return !isNaN(parseFloat(c)) && parseFloat(c) < 0;
}
function esc(s) {
  return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function rowsOf(data) {
  const r = [];
  let i = 1;
  while (data["row" + i]) {
    if (Array.isArray(data["row" + i])) r.push(data["row" + i].map((x) => (x == null ? "" : String(x))));
    i++;
  }
  return r;
}
function buildTable(data) {
  const rows = rowsOf(data);
  if (!rows.length) return "<p>No rows.</p>";
  const head = rows[0];
  const body = rows.slice(1);
  const th = head.map((h) => "<th>" + esc(h) + "</th>").join("");
  const tr = body
    .map((r) => {
      const label = r[0] || "";
      const blank = r.slice(1).every((c) => c === "");
      const cls = isHl(label) ? "hl" : blank ? "sub" : "";
      const tds = r
        .map((c, idx) => {
          const neg = idx > 0 && isNeg(c) ? ' class="neg"' : "";
          return "<td" + neg + ">" + esc(c) + "</td>";
        })
        .join("");
      return '<tr class="' + cls + '">' + tds + "</tr>";
    })
    .join("");
  return "<table><thead><tr>" + th + "</tr></thead><tbody>" + tr + "</tbody></table>";
}
function buildHtml(data) {
  const qt = data.quarter_type === "extended" ? "Extended (Q2/Q4)" : "Standard (Q1/Q3)";
  return `<!DOCTYPE html><html><head><meta charset="utf-8" /><style>
    :root{--green-900:#0f3d1e;--green-800:#1b5e20;--green-700:#2e7d32;--green-100:#e8f5e9;--ink:#10231a;--muted:#5b6b62;--line:#e3e9e5;--red:#d32f2f;}
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'DejaVu Sans','Liberation Sans',system-ui,Segoe UI,Arial,sans-serif;background:#fff;color:var(--ink);-webkit-font-smoothing:antialiased}
    .frame{display:inline-block;padding:24px;background:#fff}
    .pnl{border:1.5px solid var(--green-700);border-radius:12px;overflow:hidden;width:max-content;max-width:none}
    .pnl-head{background:linear-gradient(135deg,var(--green-800),var(--green-700));color:#fff;padding:14px 18px}
    .pnl-head .h1{font-size:17px;font-weight:800}
    .pnl-head .sub{font-size:11.5px;color:#cfe8d3;margin-top:2px}
    table{width:100%;border-collapse:collapse}
    thead th{background:var(--green-100);border-bottom:2px solid var(--green-700);padding:10px 14px;font-size:12.5px;font-weight:700;white-space:nowrap;text-align:right}
    thead th:first-child{text-align:left}
    tbody td{padding:9px 14px;font-size:12.5px;white-space:nowrap;text-align:right;border-bottom:1px solid var(--line);color:var(--ink)}
    tbody td:first-child{text-align:left}
    tbody tr.hl{background:var(--green-100)}
    tbody tr.hl td{font-weight:700}
    tbody tr.sub td:first-child{color:var(--muted);padding-left:26px;font-weight:500}
    td.neg{color:var(--red)}
    .pnl-foot{background:#f5f8f6;padding:7px 16px;text-align:right;font-size:10px;color:var(--muted);border-top:1px solid var(--line)}
  </style></head><body>
    <div class="frame"><div class="pnl">
      <div class="pnl-head"><div class="h1">${esc(data.company_name || "Unknown Company")}</div>
      <div class="sub">Quarterly Financial Results — ${qt} · All values in ₹ Crores</div></div>
      ${buildTable(data)}
      <div class="pnl-foot">Generated by Niveshaay Financial Results Processor</div>
    </div></div>
  </body></html>`;
}

// ── Browser (lazy singleton, reconnect if it dies) ───────────────────────────
let browserPromise = null;
async function getBrowser() {
  if (browserPromise) {
    try {
      const b = await browserPromise;
      if (b.connected) return b;
    } catch (_) {
      /* fall through and relaunch */
    }
  }
  browserPromise = puppeteer.launch({
    executablePath: EXECUTABLE,
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-gpu"],
  });
  return browserPromise;
}

async function renderPng(data) {
  const browser = await getBrowser();
  const page = await browser.newPage();
  try {
    await page.setViewport({ width: 1600, height: 900, deviceScaleFactor: 2 });
    await page.setContent(buildHtml(data), { waitUntil: "networkidle0" });
    const el = (await page.$(".frame")) || page;
    const buf = await el.screenshot({ type: "png" });
    return Buffer.from(buf).toString("base64");
  } finally {
    await page.close();
  }
}

// ── HTTP ─────────────────────────────────────────────────────────────────────
const app = express();
app.use(express.json({ limit: "5mb" }));

app.get("/health", (_req, res) => res.json({ ok: true }));

app.post("/generate-image", async (req, res) => {
  const data = (req.body && req.body.data) || req.body;
  if (!data || typeof data !== "object" || !data.row1) {
    return res.status(400).json({ error: "Expected JSON body { data: { row1, ... } }" });
  }
  try {
    const base64 = await renderPng(data);
    res.json({ base64 });
  } catch (e) {
    console.error("render failed:", e);
    res.status(500).json({ error: "Failed to render image: " + (e && e.message ? e.message : String(e)) });
  }
});

app.listen(PORT, () => console.log(`image-service listening on :${PORT} (chromium=${EXECUTABLE})`));
